edeal/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('store.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views
from .views import (
    AddProduct,
    AddToWishlist,
    DeleteProduct,
    Home,
    LoginView,
    Profile,
    OrderView,
    PaymentView,
    RemoveFromWishlist,
    SignUp,
    WishlistView,
    userLogout,
    venderHome,
    ProductDetail,
    CouponView,

)

app_name = "store"

urlpatterns = [
    path("", Home.as_view(), name="home"),
    path("venderHome/", venderHome.as_view(), name="venderHome"),
    path("signup/", SignUp.as_view(), name="signup"),
    path("login/", LoginView.as_view(), name="login"),
    path('profile/', Profile.as_view(), name='profile'),
    path("logout/", userLogout, name="logout"),
    path("product/<int:pk>/", ProductDetail.as_view(), name="product"),
    path("addproduct/", AddProduct.as_view(), name="addproduct"),
    path("deleteproduct/", DeleteProduct.as_view(), name="deleteproduct"),
    path("coupon/",CouponView.as_view(), name="coupon"),
    # Cart urls
    path("add/", views.cart_add, name="add"),
    path("item_clear/", views.item_clear, name="item_clear"),
    path("item_increment/", views.item_increment, name="item_increment"),
    path("item_decrement/", views.item_decrement, name="item_decrement"),
    path("cart_clear/", views.cart_clear, name="cart_clear"),
    path("cart-detail/", views.cart_detail, name="cart_detail"),
    path("payment/", PaymentView.as_view(), name="payment"),
    path("handlerequest/", views.handlerequest, name="handlerequest"),
    path("order/", OrderView.as_view(), name="order"),
    path("wishlist/", AddToWishlist.as_view(), name="wishlist"),
    path(
        "remove-from-wishlist/",
        RemoveFromWishlist.as_view(),
        name="remove-from-wishlist",
    ),
    path("wish/", WishlistView.as_view(), name="wish"),
]

store/models.py
from itertools import product
from math import dist
from pyexpat import model
from unicodedata import category
from wsgiref.simple_server import demo_app
from django.conf import settings
from django.contrib.auth.models import AbstractUser, User
from django.db import models

from .manager import UserManager

User = settings.AUTH_USER_MODEL

# Create your models here.


class User(AbstractUser):

    role = (
        ("vender", "vender"),
        ("customer", "customer"),
    )
    username = None
    email = models.EmailField(unique=True)
    mobile = models.CharField(max_length=20)
    role = models.CharField(max_length=15, choices=role)
    image = models.ImageField(upload_to="uploads/profile", default=None)

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []


class Category(models.Model):
    name = models.CharField(max_length=25)
    image = models.ImageField(upload_to="uploads/category", default=None)

    def __str__(self):
        return f"{self.name}"


class SubCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=25)
    image = models.ImageField(upload_to="uploads/category", default=None)

    def __str__(self):
        return f"{self.name}"


class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, default=None)
    sub_category = models.ForeignKey(
        SubCategory, on_delete=models.CASCADE, default=None)
    name = models.CharField(max_length=30)
    price = models.FloatField()
    specifications = models.TextField(max_length=200, null=True, blank=True)
    brand = models.CharField(
        max_length=20, default=None, null=True, blank=True)
    description = models.TextField(max_length=200, null=True, blank=True)
    image = models.ImageField(upload_to="uploads/product")
    seller = models.CharField(
        max_length=30, default=None, null=True, blank=True)
    highlight1 = models.CharField(max_length=200, null=True, blank=True)
    highlight2 = models.CharField(max_length=200, null=True, blank=True)
    highlight3 = models.CharField(max_length=200, null=True, blank=True)
    highlight4 = models.CharField(max_length=200, null=True, blank=True)
    war_summary = models.CharField(
        max_length=50, default="1 Year Onsite Warranty", null=True, blank=True)
    war_service_type = models.CharField(
        max_length=50, default="Onsite", null=True, blank=True)
    covered_in = models.CharField(
        max_length=50, default="Manufacturing Defects", null=True, blank=True)
    not_covered_in = models.CharField(
        max_length=50, default="Physical Damage", null=True, blank=True)
    domestic_war = models.CharField(
        max_length=50, default="1 Year", null=True, blank=True)

    def __str__(self):
        return f"{self.name}"


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    mobile = models.IntegerField()
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=20)
    state = models.CharField(max_length=20)
    zip_code = models.IntegerField()


class Order(models.Model):

    status = (
        ("pending", "pending"),
        ("success", "success"),
        ("failed", "failed"),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=15, choices=status, default="pending")
    date = models.DateTimeField()
    order_id = models.CharField(max_length=100, default=None, null=True)
    amount = models.FloatField()


class OrderLine(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()


class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.product}"


class Coupon(models.Model):
    coupon_type = (
        ('min', 'min'),
        ('bank', 'bank'),
        ('category', 'category'),
        ('sub_cat', 'sub_cat'),
        ('brand', 'brand'),
        ('product','product')
    )
    dis_type = (
        ('in_percentage', 'in_percentage'),
        ('in_rupees','in_rupees')
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    coupon_type = models.CharField(max_length=8, choices=coupon_type)
    min = models.IntegerField(default=None, null=True, blank=True)
    bank = models.CharField(max_length=45,default=None, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=None, null=True, blank=True)
    sub_cat = models.ForeignKey(SubCategory, on_delete=models.CASCADE, default=None, null=True, blank=True)
    brand = models.CharField(max_length=20, default=None, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, default=None, null=True, blank=True)
    coupon_code = models.CharField(max_length=6)
    discount_type = models.CharField(max_length=15, choices=dis_type)
    discount = models.IntegerField()
    upto = models.IntegerField(default=None, null=True, blank=True)
    description = models.CharField(max_length=50)
    valid_till = models.DateField(default=None)


    def __str__(self):
        return f"{self.coupon_code}"

store/views.py
import datetime

import pytz
import razorpay
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views import View
from django.views.decorators.csrf import csrf_exempt

from edeal import settings

from .cart import *
from .forms import SignupForm
from .models import (
    Address,
    Category,
    Coupon,
    Order,
    OrderLine,
    Product,
    SubCategory,
    User,
    Wishlist,
)
from .total import *

IST = pytz.timezone("Asia/Kolkata")

# Create your views here.
class CustomLoginRequiredMixin(LoginRequiredMixin):

    permission_denied_message = "You have to be logged in to access that page"

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.add_message(
                request, messages.WARNING, self.permission_denied_message
            )
            return self.handle_no_permission()
        return super(CustomLoginRequiredMixin, self).dispatch(request, *args, **kwargs)


class Home(View):
    """
    Home Page: Shows all products.
    """

    def get(self, request):
        cat_id = request.GET.get("category")
        sub_cat_id = request.GET.get("sub_cat")

        categories = Category.objects.all()
        products = Product.objects.all()
        sub_categories = SubCategory.objects.all()
        form = SignupForm()

        if cat_id:
            category = Category.objects.get(id=cat_id)
            products = Product.objects.filter(category=category)
            context = {"category": category, "products": products}
            return render(request, "store/category1.html", context)
        elif sub_cat_id:
            sub_cat = SubCategory.objects.get(id=sub_cat_id)
            products = Product.objects.filter(sub_category=sub_cat)
            brands = []
            for p in products:
                if p.brand not in brands:
                    brands.append(p.brand)
            context = {"products": products, "brands": brands}
            return render(request, "store/category1.html", context)

        context = {
            "categories": categories,
            "sub_categories": sub_categories,
            "products": products,
            "form": form,
        }
        return render(request, "store/home.html", context)


class venderHome(View):
    """
    Vender Home Page : This page shows all products of authenticated Vender.
    """

    def get(self, request):
        categories = Category.objects.all()
        products = Product.objects.filter(user=request.user)
        context = {"products": products, "categories": categories}
        return render(request, "store/venderHome.html", context)


class SignUp(View):
    """
    SignUP: User can register on E-Deal by these view.
    """

    def post(self, request):
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            message = "you have successfully registered with E-Deal."
            return JsonResponse({"message": message}, status=200)
        else:
            return JsonResponse(status=400)


class LoginView(View):
    """
    LogIn: User can LogIn to the E-Deal by these view. After successfully Logged In, user will redirected to the Customer home page or Vender home page based on their registered role.
    """

    def post(self, request):
        email = request.POST.get("email")
        password = request.POST.get("password")

        user = authenticate(email=email, password=password)

        if user is not None:
            login(request, user)
            return JsonResponse(data={"role": user.role}, status=200)

        else:
            message = "Email or Password is incorrect."
            return JsonResponse(data={"message": message}, status=400)


class Profile(CustomLoginRequiredMixin, View):
    login_url = settings.login_url
    permission_denied_message = "Please login to view your profile"

    def get(self, request):
        return render(request, "store/profile.html")

    def post(self, request):
        user = request.user
        l_name = request.POST.get("last_name")
        f_name = request.POST.get("first_name")
        email = request.POST.get("email")
        mobile = request.POST.get("mobile")
        if f_name or l_name:
            user.first_name = f_name
            user.last_name = l_name

        if email:
            user.email = email

        if mobile:

            user.mobile = mobile
        user.save()

        if user:
            message = "Product added successfully."

            return JsonResponse(
                data={
                    "f_name": request.user.first_name,
                    "l_name": request.user.last_name,
                },
                status=200,
            )
        else:
            return JsonResponse({"message": "failed"}, status=400)


def userLogout(request):
    """
    LogOut View: User will Logged Out.

    """
    logout(request)
    return redirect("store:home")


class ProductDetail(View):
    def get(self, request, pk=None):
        product = Product.objects.get(id=pk)
        context = {"product": product}
        return render(request, "store/product.html", context)


class AddProduct(CustomLoginRequiredMixin, View):

    login_url = settings.login_url
    permission_denied_message = "Please login to add your products"
    """
    AddProduct View: Vender can add their prodcut on E-Deal.

    """

    def post(self, request):
        cat_id = request.POST.get("category")
        category = Category.objects.get(id=cat_id)
        name = request.POST.get("name")
        price = request.POST.get("price")
        desc = request.POST.get("desc")
        image = request.FILES.get("p-image")
        product = Product.objects.create(
            user=request.user,
            category=category,
            name=name,
            price=price,
            description=desc,
            image=image,
        )

        if product:
            message = "Product added successfully."
            prodcut_data = User.objects.values()
            return JsonResponse({"student_data": list(prodcut_data)}, status=200)
        else:
            return JsonResponse({"message": "failed"}, status=400)


class DeleteProduct(CustomLoginRequiredMixin, View):

    login_url = settings.login_url
    permission_denied_message = "Please login to delete your products"

    """
    Delete Product View: Vender can delete their products from E-Deal.
    """

    def post(self, request):
        id = request.POST.get("pid")
        product = Product.objects.get(pk=id)
        product.delete()
        return JsonResponse(data={"message": "Data deleted successfully"}, status=200)
        

class CouponView(View):
    def get(self, request):
        context = {"coupons": Coupon.objects.all()}
        return render(request, "store/coupon.html", context)

    def post(self, request):
        id = request.POST.get("id")
        coupon = Coupon.objects.get(id=id)
        cart_amount = total(request)

        if coupon.coupon_type == "min":
            if cart_amount >= coupon.min:
                if coupon.discount_type == "in_rupees":
                    discount = coupon.discount
                else:
                    discount = (cart_amount * coupon.discount) / 100
            else:
                discount = 0

        elif coupon.coupon_type == "category":
            discounted_amount = pro_category(request, coupon.category)

            if coupon.discount_type == "in_rupees":
                if discounted_amount == 0:
                    discount = 0
                else:
                    discount = coupon.discount
            else:
                if coupon.upto:
                    if coupon.upto < (discounted_amount * coupon.discount) / 100:
                        discount = coupon.upto
                    else:
                        discount = (discounted_amount * coupon.discount) / 100
                else:
                    discount = (discounted_amount * coupon.discount) / 100

        elif coupon.coupon_type == "sub_cat":
            discounted_amount = pro_sub_category(request, coupon.sub_cat)

            if coupon.discount_type == "in_rupees":
                if discounted_amount == 0:
                    discount = 0
                else:
                    discount = coupon.discount

            else:
                if coupon.upto:
                    if coupon.upto < (discounted_amount * coupon.discount) / 100:
                        discount = coupon.upto
                    else:
                        discount = (discounted_amount * coupon.discount) / 100
                else:
                    discount = (discounted_amount * coupon.discount) / 100

        elif coupon.coupon_type == "brand":
            discounted_amount = pro_brand(request, coupon.brand)

            if coupon.discount_type == "in_rupees":
                if discounted_amount == 0:
                    discount = 0
                else:
                    discount = coupon.discount

            else:
                if coupon.upto:
                    if coupon.upto < (discounted_amount * coupon.discount) / 100:
                        discount = coupon.upto
                    else:
                        discount = (discounted_amount * coupon.discount) / 100
                else:
                    discount = (discounted_amount * coupon.discount) / 100

        elif coupon.coupon_type == "product":
            discounted_amount = prod(request, coupon.product)

            if coupon.discount_type == "in_rupees":
                if discounted_amount == 0:
                    discount = 0
                else:
                    discount = coupon.discount

store/templates/store/base.html
{% load static %}
{% load cart_tag %}
{% load cart_filter %}
{% load crispy_forms_tags %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
        integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <title>E-Deal</title>
</head>

<body>
    <div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top" id="qwe">
            <div class="container-fluid" id="q">

                <div class="row collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
                    <!-- <ul class="navbar-nav mb-2 mb-lg-0"> -->
                    <div class="col-md-2"></div>
                    <div class="col-md-2">
                        <img src="{% static 'images/Edeal.jpg' %}" id="logo" alt="">
                        <a class="navbar-brand" href="/">
                            <i> E-Deal</i>
                        </a>
                    </div>

                    <div class="col-md-3 dropdown">
                        <input class="form-control me-2" id="search" type="text"
                            placeholder="Search for products and more" role="button" autocomplete="off"
                            id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false" onkeyup="search()">

                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            {% for product in products %}
                            <li class="s-product"><a class="dropdown-item"
                                    href="{% url 'store:product' product.id %}">{{product.name}}</a></li>
                            {% endfor %}
                        </ul>
                    </div>

                    <div class="col nav-font">
                        <!-- <li class="nav-item m-2"> -->
                        {% if request.user.is_authenticated %}
                        <button type="button" class="form-control me-2" data-bs-toggle="modal"
                            data-bs-target="#loginmodal" data-bs-whatever="@mdo"
                            id="loginid">{{request.user.first_name}} <i class="fa fa-chevron-down"
                                aria-hidden="true"></i>
                        </button>
                        <div class="dropdown-content">
                            <hr class="line">
                            <a href="{% url 'store:profile' %}"><i class="fa fa-user-circle user"
                                    aria-hidden="true"></i>
                                My Profile</a>
                            <hr class="line">
                            <a href="{% url 'store:order' %}"><i class="fa fa-window-restore user"
                                    aria-hidden="true"></i> Orders</a>
                            <hr class="line">
                            <a href="{% url 'store:wish' %}" class="pb-2"><i class="fa fa-heart user"
                                    aria-hidden="true"></i>
                                Wishlist</a>
                            <hr class="line">

                            <a href="{% url 'store:coupon' %}" class="pb-2"><i class="fa fa-window-maximize user" aria-hidden="true"></i>
                                Coupons</a>
                            <hr class="line">

                            <a href="" class="pb-2"><i class="fa fa-bell user" aria-hidden="true"></i>
                                Notifications</a>
                            <hr class="line">

                            <a href="{% url 'store:logout' %}" class="pb-2"><i class="fa fa-thermometer-empty user"
                                    aria-hidden="true"></i>
                                Logout</a>
                        </div>
                        {% else %}

                        <button type="button" class="form-control me-2" data-bs-toggle="modal"
                            data-bs-target="#loginmodal" data-bs-whatever="@mdo" id="loginid">Login</button>
                        <div class="dropdown-content">
                            <a href="" id="signup-a" data-bs-toggle="modal" data-bs-target="#exampleModal"
                                data-bs-whatever="@mdo"> <span class="dd-su"><b>New User?</b></span> <span>Sign
                                    Up</span>
                            </a>
                            <hr class="line">
                            <a href="{% url 'store:profile' %}"><i class="fa fa-user-circle user" aria-hidden="true"></i>
                                My Profile</a>
                            <hr class="line">
                            <a href="{% url 'store:order' %}"><i class="fa fa-window-restore user"
                                    aria-hidden="true"></i> Orders</a>
                            <hr class="line">
                            <a href="{% url 'store:wish' %}" class="pb-2"><i class="fa fa-heart user"
                                    aria-hidden="true"></i>
                                Wishlist</a>
                            <hr class="line">

                    
                        </div>
                        {% endif %}
                    </div>
                    <!-- <div class="col"> -->
                    <div class="col btn-group  nav-font">
                        <button class="form-control me-2 dropdown-toggle" id="dropdownMenuButton"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            More
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <li><a class="dropdown-item" href="#">Menu item</a></li>
                            <li><a class="dropdown-item" href="#">Menu item</a></li>
                            <li><a class="dropdown-item" href="#">Menu item</a></li>
                        </ul>
                    </div>

                    <!-- </div> -->

                    <div class="col nav-font">

                        <a class="navbar-brand" href="{% url 'store:cart_detail' %}">
                            <i class="fa fa-shopping-cart" aria-hidden="true"></i> Cart<span
                                id="nav-cart">({{request.session.cart|cart_quantity}})</span>
                        </a>
                    </div>
                    <div class="col-md-2"></div>

                    <!-- 
                        {% if request.user.is_authenticated %}
                        
                        <li class="nav-item">
                            <a class="nav-link active mr-5" aria-current="page" href="" style="font-size:20px;">Welcome {{request.user.first_name}}</a>
                        </li>
                            {% if request.user.role == "customer" %}
                        <li class="nav-item t">
                            <a class="nav-link" href="{% url 'store:wish' %}">Whislist <span class="badge bg-danger" id="nav-wishlist">{{request.user|wishlist_quantity}}</span></a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'store:cart_detail' %}">Cart <span class="badge bg-primary" id="nav-cart">{{request.session.cart|cart_quantity}}</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'store:order' %}" style="font-size:17px;">Order</a>
                        </li> -->
                    <!-- {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'store:logout' %}" style="font-size:17px;">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item m-2">
                            <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                                data-bs-target="#exampleModal" data-bs-whatever="@mdo">SignUp</button>
                        </li> -->
                    <!-- <div class="col">
                        <li class="nav-item m-2">
                            <button type="button" class="btn btn-success" data-bs-toggle="modal"
                                data-bs-target="#loginmodal" data-bs-whatever="@mdo" id="loginid">LogIn</button>
                        </div>
                         {% endif %}  -->

                </div>
            </div>
        </nav>

        <!-- SignUP Modal -->

        {% block content %}

        {% endblock %}


    </div>





    <!-- Login Modal -->

    <div class="modal fade" id="loginmodal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Please Login here...!</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div id="login-error" class="alert alert-danger" style="display:none;"> </div>

                    <form action="" method="POST">
                        {% csrf_token %}

                        <div class="form-group">
                            <label for="email-id" class="col-form-label">Email:</label>
                            <input required type="email" name="email" id="email-id"
                                class=" form-control-sm form-control" placeholder="example@gmail.com">
                            <p id="email-error" style="display: none;"></p>
                        </div>
                        <div class="form-group">
                            <label for="pass-id">Password</label>
                            <input type="password" name="password" id="pass-id" class="form-control form-control-sm"
                                placeholder="********">
                            <p id="pass-error" style="display: none;"></p>
                        </div>

                        <div class="row">
                            <div class="form-group col-md-3 mt-2">
                                <button type="button" id="login-btn" class="btn btn-sm btn-info">Login</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script> -->

    <!-- Option 2: Separate Popper and Bootstrap JS -->

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>

    {% load static %}
    <script src="{% static 'js/jquery.js' %}"></script>

    <script src="{% static 'js/custom.js' %}"></script>


</body>

</html>

store/templates/store/failed.html
<h2>Failed</h2>

store/templates/store/success.html
{% extends 'store/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <section class="content-box">
        <script>
            Swal.fire(
                'Placed!',
                'Your order has been placed!',
                'success'
            )
            
            document.querySelector(".swal2-confirm").addEventListener("click", function () {
                window.location.href = 'http://127.0.0.1:8000/';
            });
        </script>
    </section>
</div>
{% endblock %}